spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/quickmealsauth
    username: root
    password: ilovemylife69
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka