spring:
  application:
    name: EDGE-SERVER
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
  server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring.cloud.gateway.routes:
  - id: auth-service
    uri: lb://AUTH-SERVICE
    predicates:
      - Path=/auth-service/auth/**

  - id: auth-service-user
    uri: lb://AUTh-SERVICE
    predicates:
      - Path=/auth-service/user/**
    filters:
      - AuthPredicateFactory

  - id: product-service
    uri: lb://PRODUCT-SERVICE
    predicates:
      - Path=/product-service/**

  - id: order-service
    uri: lb://ORDER-SERVICE
    predicates:
      - Path=/order-service/**
